services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: redis:7-alpine
    networks:
      - backend
  celery:
    build: .
    command:
      - celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

  celery-beat:
    build: .
    command:
      - celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend
volumes:
  static_volume:
  media_volume:

networks:
  backend:

