# Generated by Django 5.2.1 on 2025-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
