name: CD -> VPS (Supervisorlar bilan)

on:
  push:
    branches:
      - main
      -
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Restart Supervisor program on VPS"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: '22'

          script: |
            set -e
            
            cd /home/${{ secrets.SERVER_USER }}/DRF-normativlar
            
            git stash || true
            
            git pull --rebase origin main
            
            source venv/bin/activate
            pip install -r requirements.txt
            export DJANGO_SETTINGS_MODULE="config.settings"
            python3 manage.py migrate --noinput
            python3 manage.py collectstatic --noinput
            
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart drf_normativ
            sudo supervisorctl restart celery-worker
            sudo supervisorctl restart celery-beat
            
            sudo nginx -t && sudo systemctl reload nginx
            
            echo "Successfully finished CD"
            
