name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: test
      DEBUG: True
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test
      DB_HOST: localhost
      REDIS_HOST: redis://localhost
      REDIS_PORT: 6379
      CELERY_BROKER_URL: 'redis://localhost:6379/0'
      CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
      EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587
      EMAIL_USE_TLS: True
      EMAIL_HOST_USER: 'email'
      EMAIL_HOST_PASSWORD: 'test'


    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2

        with:
          python-version: 3.13
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test